<?php

declare( strict_types=1 );

namespace Paumalu\SiteSurvey\Setup;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Capability names for the survey post type, plus the workflow caps that gate review and sending.
 */
final class Capabilities {

	public const TECHNICIAN_ROLE = 'pe_technician';

	/** Gates the review screen and the accept / request-changes transitions. */
	public const REVIEW = 'pe_review_site_surveys';

	/** Gates emailing a proposal to a customer. */
	public const SEND_PROPOSAL = 'pe_send_proposal';

	/**
	 * The post-type capability set generated by capability_type => ['site_survey','site_surveys'].
	 *
	 * @return array<string, string>
	 */
	public static function post_type_caps(): array {
		return [
			'edit_post'              => 'edit_site_survey',
			'read_post'              => 'read_site_survey',
			'delete_post'            => 'delete_site_survey',
			'edit_posts'             => 'edit_site_surveys',
			'edit_others_posts'      => 'edit_others_site_surveys',
			'publish_posts'          => 'publish_site_surveys',
			'read_private_posts'     => 'read_private_site_surveys',
			'delete_posts'           => 'delete_site_surveys',
			'delete_private_posts'   => 'delete_private_site_surveys',
			'delete_published_posts' => 'delete_published_site_surveys',
			'delete_others_posts'    => 'delete_others_site_surveys',
			'edit_private_posts'     => 'edit_private_site_surveys',
			'edit_published_posts'   => 'edit_published_site_surveys',
			'create_posts'           => 'edit_site_surveys',
		];
	}

	/**
	 * Technicians create and edit their own surveys and nothing else.
	 *
	 * Note the omissions: no publish_site_surveys (so they cannot self-approve), no
	 * edit_others_site_surveys (so they never see another tech's work), and no *_posts or
	 * *_pages caps at all, so the rest of the site is closed to them.
	 *
	 * @return array<string, bool>
	 */
	public static function technician_caps(): array {
		return [
			'read'                          => true,
			'upload_files'                  => true,
			'edit_site_surveys'             => true,
			'edit_published_site_surveys'   => true,
			'delete_site_surveys'           => true,
			'publish_site_surveys'          => false,
			'edit_others_site_surveys'      => false,
			'delete_others_site_surveys'    => false,
			'delete_published_site_surveys' => false,
			'read_private_site_surveys'     => false,
			self::REVIEW                    => false,
			self::SEND_PROPOSAL             => false,
		];
	}

	/**
	 * Full access, granted to editor and administrator.
	 *
	 * @return list<string>
	 */
	public static function reviewer_caps(): array {
		return [
			'edit_site_surveys',
			'edit_others_site_surveys',
			'edit_published_site_surveys',
			'edit_private_site_surveys',
			'publish_site_surveys',
			'read_private_site_surveys',
			'delete_site_surveys',
			'delete_others_site_surveys',
			'delete_published_site_surveys',
			'delete_private_site_surveys',
			self::REVIEW,
			self::SEND_PROPOSAL,
		];
	}
}
